"""Deterministic template generator (milestone 1: no LLM).

Emits ordered Falco YAML: macros first, then the rule. Only fields declared in
the detection spec appear in output.
"""
from __future__ import annotations

import yaml


def generate_rule(spec, profile=None) -> list[dict]:
    match = spec.match
    proc = match["proc.name"]
    evt = match.get("evt.type", "execve")

    cond_parts = ["spawned_process", f'proc.name = "{proc}"']
    for fld, vals in match.get("scope", {}).items():
        quoted = ", ".join(f'"{v}"' for v in vals)
        cond_parts.append(f"{fld} in ({quoted})")
    condition = " and ".join(cond_parts)

    output_field_list = list(spec.required_fields)
    for f in ["proc.cmdline", "user.name", "k8s.pod.name", "container.image.repository"]:
        if f not in output_field_list and (profile is None or profile.field_supported(f)):
            output_field_list.append(f)

    output_fields_str = " ".join(f"{f}=%{f}" for f in output_field_list)
    rule_name = f"AFB {' '.join(w.capitalize() for w in proc.split())} Execution"

    rule_doc = [
        {
            "macro": "afb_spawned_process",
            "condition": "evt.type in (execve, execveat) and evt.dir = <",
        },
        {
            "rule": rule_name,
            "desc": f"Generated by auto-falco-rule-builder: {spec.intent}",
            "condition": f"afb_spawned_process and {condition}",
            "output": f"{rule_name} ({output_fields_str})",
            "priority": "WARNING",
            "tags": ["afb", "process", "auto-generated"],
        },
    ]
    return rule_doc


def render_yaml(rule_doc: list[dict]) -> str:
    return yaml.safe_dump(rule_doc, sort_keys=False, default_flow_style=False)
